GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTZmNDZmMjI3OGVmNDI5NDFkYWQ4YWIiLCJlbWFpbCI6ImFobWFkQGdtYWlsLmNvbSIsImlhdCI6MTcwMTg2NDc4MywiZXhwIjoxNzAxODY0ODAzfQ.D-0HlWo90BSQl3PkeptZxYTiSE3fU0LYZ-n3Sauju6c

###
GET http://localhost:5000/products

###
GET http://localhost:5000/users/656f3e954794e6904c119f72
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJBaG1hZCBGaWtyaSBIYWlrYWwiLCJlbWFpbCI6ImhhaWthbEBnbWFpbC5jb20iLCJpYXQiOjE2ODk3ODc2ODUsImV4cCI6MTY4OTg3NDA4NX0.SW61oHxU8lhc_mI8q1XP78GVYpxRgoWZZccONOEwJdI

###
GET http://localhost:5000/products/1

###
POST http://localhost:5000/users/
Content-Type: application/json

{
  "name": "ahmad",
  "email": "ahmad@gmail.com",
  "password": "ahmad123",
  "confPassword" : "ahmad123"
}

###
POST http://localhost:5000/products/
Content-Type: application/json

{
  "image": "/src/assets/product-images/AlmondChoco.png",
  "title": "Almond Choco",
  "price": 39000,
  "desc": "Cokelat klasik dari Fore Coffee yang dipadu dengan susu almond. Sebuah definisi comfort drink yang sesungguhnya.",
  "category": "Non-Coffee"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "ahmad@gmail.com",
  "password": "ahmad123"
}

###
DELETE http://localhost:5000/logout

###
GET http://localhost:5000/token

###
PATCH  http://localhost:5000/users/656f3e954794e6904c119f72
Content-Type: application/json

{
  "fullname": "FikalAhmad",
  "email": "fikalahmad@gmail.com"
}
###
PATCH  http://localhost:5000/products/1
Content-Type: application/json

{
  "image": "/src/assets/product-images/ArenLatte.png",
  "title": "Aren Latte",
  "price": 29000,
  "desc": "Rasa alami gula aren berpadu sempurna dengan espresso premium",
  "category": "Signature"
}

###
DELETE  http://localhost:5000/users/2
