GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJBaG1hZCBGaWtyaSBIYWlrYWwiLCJlbWFpbCI6ImhhaWthbEBnbWFpbC5jb20iLCJpYXQiOjE2ODk3ODc2ODUsImV4cCI6MTY4OTc4NzcwNX0.jh1MxW3ZNQ2azXj_va_31rH_2fjVPJwcRkRrN6w26z0

###
GET http://localhost:5000/products

###
GET http://localhost:5000/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsIm5hbWUiOiJBaG1hZCBGaWtyaSBIYWlrYWwiLCJlbWFpbCI6ImhhaWthbEBnbWFpbC5jb20iLCJpYXQiOjE2ODk3ODc2ODUsImV4cCI6MTY4OTg3NDA4NX0.SW61oHxU8lhc_mI8q1XP78GVYpxRgoWZZccONOEwJdI

###
GET http://localhost:5000/products/1

###
POST http://localhost:5000/users/
Content-Type: application/json

{
  "name": "Ahmad Fikri Haikal",
  "email": "haikal2@gmail.com",
  "password": "haikal1234",
  "confPassword" : "haikal1234"
}

###
POST http://localhost:5000/products/
Content-Type: application/json

{
  "image": "/src/assets/product-images/IrishLatte.png",
  "title": "Caramel Praline Macchiato",
  "price": 33000,
  "desc": "Latte dengan saus Praline dan karamel dengan rasa dan aroma manis.",
  "category": "Signature"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
  "email": "haikal@gmail.com",
  "password": "haikal123"
}

###
DELETE http://localhost:5000/logout

###
GET http://localhost:5000/token

###
PATCH  http://localhost:5000/users/1
Content-Type: application/json

{
  "firstName": "Ahmad",
  "lastName": "Fikri Haikal",
  "email": "fikaalm26@gmail.com",
  "password": "Fikaalm26123",
  "reppass": "Fikaalm26123"
}
###
PATCH  http://localhost:5000/products/1
Content-Type: application/json

{
  "image": "/src/assets/product-images/ArenLatte.png",
  "title": "Aren Latte",
  "price": 29000,
  "desc": "Rasa alami gula aren berpadu sempurna dengan espresso premium",
  "category": "Signature"
}

###
DELETE  http://localhost:5000/users/2
